server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/safeview
    username: root
    password: dnjswnsdud1.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true